<?php
declare(strict_types=1);

return [
    'BlazeCast' => [
        'logging' => [
            'enabled' => env('BLAZECAST_LOGGING_ENABLED', true),
            'debug_enabled' => env('BLAZECAST_LOGGING_DEBUG_ENABLED', false),
            'log_file' => env('BLAZECAST_LOGGING_FILE', 'blazecast'),
            'log_path' => env('BLAZECAST_LOGGING_PATH', LOGS),
            'scopes' => [
                'command.server' => true,
                'command.server.start' => true,
                'rhythm.recorder' => true,
                'rhythm.recorder.messages' => true,
                'rhythm.recorder.connections' => true,
                'socket.server' => true,
                'socket.server.redis' => true,
                'socket.server.rhythm' => true,
                'socket.server.restart' => true,
                'socket.server.disconnect' => true,
                'socket.connection' => true,
                'socket.connection.ping' => true,
                'socket.connection.pong' => true,
                'socket.connection.control' => true,
                'socket.connection.events' => true,
                'socket.controller' => true,
                'socket.controller.auth' => true,
                'socket.controller.events' => true,
                'socket.controller.factory' => true,
                'socket.controller.response' => true,
                'socket.controller.users' => true,
                'socket.channel' => true,
                'socket.channel.pusher' => true,
                'socket.channel.factory' => true,
                'socket.channel.serialization' => true,
                'socket.channel.cache' => true,
                'socket.channel.private' => true,
                'socket.manager' => true,
                'socket.manager.channel' => true,
                'socket.manager.connection' => true,
                'socket.manager.application' => true,
                'socket.manager.operations' => true,
                'socket.registry' => true,
                'socket.registry.connection' => true,
                'socket.registry.context' => true,
                'socket.handler' => true,
                'socket.handler.pusher' => true,
                'socket.handler.dispatcher' => true,
                'socket.router' => true,
                'socket.router.loader' => true,
                'socket.http' => true,
                'socket.http.processor' => true,
                'socket.metrics' => true,
                'socket.job' => true,
                'socket.job.manager' => true,
            ],
            'disabled_scopes' => [
            ],
        ],
    ],
];

